import type {
	Activity,
	Contact,
	CrmTask,
	Lead,
	Message,
	Property,
	TeamMember,
} from "./types";

/**
 * Fictional demonstration dataset for the Collabimmo CRM. All records are
 * invented and are not connected to any live client-facing data. Dates are
 * anchored around mid-2026 so the timeline reads naturally in the demo.
 */

export const TEAM: TeamMember[] = [
	{
		id: "u1",
		name: "Nicolas Dubois",
		role: "Directeur associé",
		initials: "ND",
	},
	{
		id: "u2",
		name: "Camille Lefèvre",
		role: "Négociatrice senior",
		initials: "CL",
	},
	{
		id: "u3",
		name: "Thomas Mertens",
		role: "Conseiller investissement",
		initials: "TM",
	},
	{
		id: "u4",
		name: "Sophie Laurent",
		role: "Responsable relation clients",
		initials: "SL",
	},
];

export const LEADS: Lead[] = [
	{
		id: "l1",
		name: "Élise Vandenberghe",
		company: "Groupe Vandenberghe Invest",
		role: "Directrice des acquisitions",
		email: "e.vandenberghe@gv-invest.be",
		phone: "+32 475 21 44 08",
		source: "Référence",
		stage: "negotiation",
		priority: "high",
		value: 2450000,
		propertyInterest:
			"Immeuble de bureaux clé-en-main, 1 800 m², axe Bruxelles-Namur",
		propertyType: "office",
		location: "Wavre",
		owner: "Nicolas Dubois",
		createdAt: "2026-05-12T09:20:00Z",
		lastActivityAt: "2026-07-15T14:05:00Z",
		tags: ["Off-market", "Investisseur institutionnel"],
		notes:
			"Prête à signer sous 60 jours. Attend le rapport technique du bâtiment de Wavre. Financement déjà validé par ING.",
	},
	{
		id: "l2",
		name: "Marc Delhaize",
		company: "Delhaize Logistics SA",
		role: "COO",
		email: "marc.delhaize@dlog.be",
		phone: "+32 496 78 12 90",
		source: "Site web",
		stage: "proposal",
		priority: "high",
		value: 3800000,
		propertyInterest: "Entrepôt logistique 6 500 m² avec quais, proximité E42",
		propertyType: "warehouse",
		location: "Charleroi",
		owner: "Thomas Mertens",
		createdAt: "2026-06-01T11:00:00Z",
		lastActivityAt: "2026-07-14T09:30:00Z",
		tags: ["Logistique", "Urgent"],
		notes:
			"Proposition envoyée le 10/07. Souhaite une option d'extension sur terrain adjacent.",
	},
	{
		id: "l3",
		name: "Aurélie Simon",
		company: "Cabinet Simon & Associés",
		role: "Fondatrice",
		email: "a.simon@simon-avocats.be",
		phone: "+32 471 33 09 55",
		source: "LinkedIn",
		stage: "qualified",
		priority: "medium",
		value: 620000,
		propertyInterest:
			"Plateau de bureaux 240 m² en centre-ville, standing élevé",
		propertyType: "office",
		location: "Namur",
		owner: "Camille Lefèvre",
		createdAt: "2026-06-18T08:45:00Z",
		lastActivityAt: "2026-07-12T16:20:00Z",
		tags: ["Profession libérale"],
		notes:
			"Visite prévue. Budget confirmé, sensible à la localisation et au parking.",
	},
	{
		id: "l4",
		name: "Karim Benali",
		company: "Benali Retail Group",
		role: "CEO",
		email: "k.benali@benaliretail.be",
		phone: "+32 478 90 11 23",
		source: "Salon MIPIM",
		stage: "contacted",
		priority: "high",
		value: 1750000,
		propertyInterest:
			"Surface commerciale de plain-pied 900 m², forte visibilité",
		propertyType: "retail",
		location: "Liège",
		owner: "Camille Lefèvre",
		createdAt: "2026-07-02T10:15:00Z",
		lastActivityAt: "2026-07-13T11:40:00Z",
		tags: ["Retail", "Expansion"],
		notes:
			"Cherche 3 emplacements en Wallonie sur 18 mois. Décisionnaire direct.",
	},
	{
		id: "l5",
		name: "Isabelle Moreau",
		company: "Fondation Moreau",
		role: "Administratrice",
		email: "i.moreau@fondation-moreau.org",
		phone: "+32 493 45 67 88",
		source: "Site web",
		stage: "new",
		priority: "medium",
		value: 980000,
		propertyInterest: "Immeuble mixte à rénover, potentiel bureaux + logements",
		propertyType: "mixed",
		location: "Mons",
		owner: "Sophie Laurent",
		createdAt: "2026-07-16T07:50:00Z",
		lastActivityAt: "2026-07-16T07:50:00Z",
		tags: ["À rénover"],
		notes: "Nouvelle demande via le formulaire de contact. À qualifier.",
	},
	{
		id: "l6",
		name: "Pierre-Yves Lambert",
		company: "PYL Développement",
		role: "Promoteur",
		email: "py.lambert@pyl-dev.be",
		phone: "+32 477 22 88 41",
		source: "Référence",
		stage: "new",
		priority: "high",
		value: 4200000,
		propertyInterest: "Terrain agricole 4,2 ha à développer, permis en cours",
		propertyType: "land",
		location: "Gembloux",
		owner: "Nicolas Dubois",
		createdAt: "2026-07-15T13:10:00Z",
		lastActivityAt: "2026-07-15T13:10:00Z",
		tags: ["Off-market", "Développement"],
		notes:
			"Opportunité off-market. Vérifier le statut du permis avant premier RDV.",
	},
	{
		id: "l7",
		name: "Nathalie Georges",
		company: "Georges & Fils",
		role: "Gérante",
		email: "n.georges@georgesfils.be",
		phone: "+32 494 10 55 32",
		source: "Téléphone",
		stage: "qualified",
		priority: "low",
		value: 340000,
		propertyInterest: "Petit local commercial 120 m² à louer, centre",
		propertyType: "retail",
		location: "Nivelles",
		owner: "Sophie Laurent",
		createdAt: "2026-06-25T09:00:00Z",
		lastActivityAt: "2026-07-10T10:00:00Z",
		tags: ["Location"],
		notes: "Budget serré, flexible sur la date d'entrée.",
	},
	{
		id: "l8",
		name: "David Peeters",
		company: "Peeters Industries",
		role: "Directeur financier",
		email: "d.peeters@peeters-ind.be",
		phone: "+32 472 61 20 17",
		source: "Site web",
		stage: "contacted",
		priority: "medium",
		value: 2100000,
		propertyInterest: "Hall industriel 3 200 m² avec bureaux attenants",
		propertyType: "industrial",
		location: "Seraing",
		owner: "Thomas Mertens",
		createdAt: "2026-06-28T14:30:00Z",
		lastActivityAt: "2026-07-11T15:45:00Z",
		tags: ["Industriel"],
		notes: "Relocalisation de production. Timing flexible sur 12 mois.",
	},
	{
		id: "l9",
		name: "Claire Dumont",
		company: "Dumont Patrimoine",
		role: "Family office",
		email: "c.dumont@dumont-patrimoine.be",
		phone: "+32 470 88 34 12",
		source: "Référence",
		stage: "won",
		priority: "high",
		value: 1650000,
		propertyInterest: "Immeuble de rapport 6 unités, rendement > 6%",
		propertyType: "mixed",
		location: "Louvain-la-Neuve",
		owner: "Nicolas Dubois",
		createdAt: "2026-04-08T09:00:00Z",
		lastActivityAt: "2026-07-08T12:00:00Z",
		tags: ["Investisseur", "Rendement"],
		notes: "Acte signé le 08/07. Recherche déjà un second bien similaire.",
	},
	{
		id: "l10",
		name: "Olivier Renard",
		company: "Renard & Co",
		role: "Directeur",
		email: "o.renard@renardco.be",
		phone: "+32 495 77 21 09",
		source: "Salon Realty",
		stage: "proposal",
		priority: "medium",
		value: 890000,
		propertyInterest: "Bureaux 450 m² avec 15 emplacements de parking",
		propertyType: "office",
		location: "Ottignies",
		owner: "Camille Lefèvre",
		createdAt: "2026-06-10T10:30:00Z",
		lastActivityAt: "2026-07-09T09:15:00Z",
		tags: ["Bureaux"],
		notes: "Compare deux biens. Décision attendue fin juillet.",
	},
	{
		id: "l11",
		name: "Fatima El Amrani",
		company: "El Amrani Franchising",
		role: "Responsable expansion",
		email: "f.elamrani@ea-franchise.be",
		phone: "+32 476 54 32 10",
		source: "LinkedIn",
		stage: "contacted",
		priority: "medium",
		value: 540000,
		propertyInterest: "Cellule commerciale 200 m² en zone de chalandise",
		propertyType: "retail",
		location: "Wavre",
		owner: "Sophie Laurent",
		createdAt: "2026-07-04T08:20:00Z",
		lastActivityAt: "2026-07-12T13:00:00Z",
		tags: ["Franchise", "Retail"],
		notes: "Cherche à ouvrir 2 points de vente cette année.",
	},
	{
		id: "l12",
		name: "Grégoire Wauters",
		company: "Wauters Holding",
		role: "Administrateur délégué",
		email: "g.wauters@wauters-holding.be",
		phone: "+32 479 12 65 44",
		source: "Référence",
		stage: "lost",
		priority: "low",
		value: 1200000,
		propertyInterest: "Bureaux 700 m² proximité gare",
		propertyType: "office",
		location: "Namur",
		owner: "Thomas Mertens",
		createdAt: "2026-05-02T09:00:00Z",
		lastActivityAt: "2026-06-30T16:00:00Z",
		tags: ["Perdu"],
		notes: "A finalement opté pour un bien via un confrère. Rester en contact.",
	},
	{
		id: "l13",
		name: "Sandrine Collard",
		company: "Collard Notaires",
		role: "Notaire",
		email: "s.collard@collard-notaires.be",
		phone: "+32 471 65 43 21",
		source: "Site web",
		stage: "negotiation",
		priority: "medium",
		value: 730000,
		propertyInterest: "Étude notariale 320 m², rez commercial",
		propertyType: "office",
		location: "Tournai",
		owner: "Camille Lefèvre",
		createdAt: "2026-05-28T11:15:00Z",
		lastActivityAt: "2026-07-14T10:20:00Z",
		tags: ["Profession libérale"],
		notes:
			"Négociation sur le prix, écart de 25 k€. Marge de manœuvre côté vendeur.",
	},
	{
		id: "l14",
		name: "Vincent Hubert",
		company: "Hubert Automotive",
		role: "Propriétaire",
		email: "v.hubert@hubert-auto.be",
		phone: "+32 498 30 22 66",
		source: "Téléphone",
		stage: "qualified",
		priority: "high",
		value: 1980000,
		propertyInterest: "Showroom + atelier 2 400 m² en bord de nationale",
		propertyType: "retail",
		location: "Arlon",
		owner: "Thomas Mertens",
		createdAt: "2026-06-20T09:40:00Z",
		lastActivityAt: "2026-07-13T14:50:00Z",
		tags: ["Automobile"],
		notes: "Financement en cours de validation. Très motivé.",
	},
];

export const MESSAGES: Message[] = [
	{
		id: "m1",
		channel: "form",
		fromName: "Isabelle Moreau",
		fromEmail: "i.moreau@fondation-moreau.org",
		company: "Fondation Moreau",
		subject: "Demande d'information — immeuble mixte à Mons",
		body: "Bonjour,\n\nNous étudions l'acquisition d'un immeuble mixte à rénover dans la région de Mons, avec un potentiel de bureaux et de logements. Pourriez-vous nous présenter vos opportunités actuelles ainsi qu'une estimation des délais ?\n\nBien à vous,\nIsabelle Moreau",
		receivedAt: "2026-07-16T07:50:00Z",
		read: false,
		starred: true,
		leadId: "l5",
	},
	{
		id: "m2",
		channel: "email",
		fromName: "Pierre-Yves Lambert",
		fromEmail: "py.lambert@pyl-dev.be",
		company: "PYL Développement",
		subject: "Terrain Gembloux — confidentiel",
		body: "Nicolas,\n\nMerci pour l'appel. Peux-tu m'envoyer le dossier complet du terrain de 4,2 ha à Gembloux ? Je souhaite le présenter à mon comité d'investissement la semaine prochaine. Le statut du permis reste le point clé.\n\nMerci,\nPY",
		receivedAt: "2026-07-15T13:10:00Z",
		read: false,
		starred: true,
		leadId: "l6",
	},
	{
		id: "m3",
		channel: "email",
		fromName: "Élise Vandenberghe",
		fromEmail: "e.vandenberghe@gv-invest.be",
		company: "Groupe Vandenberghe Invest",
		subject: "RE: Rapport technique — bureaux Wavre",
		body: "Bonjour Nicolas,\n\nParfait pour le rapport technique. Dès réception, nous pourrons fixer la date de signature. Notre financement ING est confirmé. Comptons signer avant la fin du trimestre.\n\nCordialement,\nÉlise",
		receivedAt: "2026-07-15T14:05:00Z",
		read: true,
		starred: false,
		leadId: "l1",
	},
	{
		id: "m4",
		channel: "form",
		fromName: "Karim Benali",
		fromEmail: "k.benali@benaliretail.be",
		company: "Benali Retail Group",
		subject: "Recherche 3 emplacements retail en Wallonie",
		body: "Bonjour,\n\nSuite à notre rencontre au MIPIM, je confirme notre intérêt pour 3 surfaces commerciales de plain-pied (700-1000 m²) à forte visibilité en Wallonie sur les 18 prochains mois. Quelles sont vos disponibilités pour un premier point ?\n\nKarim Benali",
		receivedAt: "2026-07-13T11:40:00Z",
		read: true,
		starred: true,
		leadId: "l4",
	},
	{
		id: "m5",
		channel: "email",
		fromName: "Sandrine Collard",
		fromEmail: "s.collard@collard-notaires.be",
		company: "Collard Notaires",
		subject: "Contre-proposition — étude Tournai",
		body: "Bonjour Camille,\n\nAprès réflexion, nous pouvons monter à 705 000 €, sous réserve de la prise en charge des travaux de mise en conformité par le vendeur. Merci de revenir vers moi.\n\nSandrine Collard",
		receivedAt: "2026-07-14T10:20:00Z",
		read: false,
		starred: false,
		leadId: "l13",
	},
	{
		id: "m6",
		channel: "whatsapp",
		fromName: "Vincent Hubert",
		fromEmail: "v.hubert@hubert-auto.be",
		company: "Hubert Automotive",
		subject: "Showroom Arlon — financement",
		body: "Bonjour Thomas, ma banque me confirme un accord de principe. On peut avancer sur la visite cette semaine ? Merci !",
		receivedAt: "2026-07-13T14:50:00Z",
		read: true,
		starred: false,
		leadId: "l14",
	},
	{
		id: "m7",
		channel: "email",
		fromName: "Marc Delhaize",
		fromEmail: "marc.delhaize@dlog.be",
		company: "Delhaize Logistics SA",
		subject: "Option d'extension — entrepôt Charleroi",
		body: "Thomas,\n\nLa proposition est intéressante. Point bloquant : nous voulons sécuriser une option sur le terrain adjacent pour une extension future. Est-ce négociable avec le propriétaire ?\n\nMarc",
		receivedAt: "2026-07-14T09:30:00Z",
		read: true,
		starred: true,
		leadId: "l2",
	},
	{
		id: "m8",
		channel: "form",
		fromName: "Julie Fontaine",
		fromEmail: "julie.fontaine@gmail.com",
		subject: "Estimation de mon bien commercial",
		body: "Bonjour,\n\nJe possède un local commercial de 180 m² à Charleroi et j'aimerais obtenir une estimation en vue d'une vente. Proposez-vous ce service ?\n\nMerci d'avance,\nJulie Fontaine",
		receivedAt: "2026-07-12T18:22:00Z",
		read: false,
		starred: false,
	},
	{
		id: "m9",
		channel: "email",
		fromName: "Aurélie Simon",
		fromEmail: "a.simon@simon-avocats.be",
		company: "Cabinet Simon & Associés",
		subject: "Disponibilités pour visite — Namur",
		body: "Bonjour Camille,\n\nJe serais disponible mardi ou jeudi après-midi pour visiter le plateau de bureaux en centre-ville. Le parking reste un critère important pour nous.\n\nBien cordialement,\nAurélie Simon",
		receivedAt: "2026-07-12T16:20:00Z",
		read: true,
		starred: false,
		leadId: "l3",
	},
	{
		id: "m10",
		channel: "phone",
		fromName: "Standard — appel manqué",
		fromEmail: "—",
		subject: "Appel manqué : promoteur région Liège",
		body: "Appel manqué à 09:12. Le correspondant souhaite discuter d'un portefeuille de 3 immeubles de bureaux à Liège. A laissé un numéro : +32 477 00 11 22. À rappeler.",
		receivedAt: "2026-07-16T09:12:00Z",
		read: false,
		starred: false,
	},
	{
		id: "m11",
		channel: "email",
		fromName: "David Peeters",
		fromEmail: "d.peeters@peeters-ind.be",
		company: "Peeters Industries",
		subject: "Hall industriel Seraing — questions techniques",
		body: "Bonjour Thomas,\n\nQuelques questions avant d'avancer : quelle est la hauteur libre sous plafond du hall de Seraing, et la puissance électrique disponible ? Ces éléments sont déterminants pour notre process.\n\nDavid Peeters",
		receivedAt: "2026-07-11T15:45:00Z",
		read: true,
		starred: false,
		leadId: "l8",
	},
	{
		id: "m12",
		channel: "form",
		fromName: "Bureau d'architectes Lombard",
		fromEmail: "contact@lombard-archi.be",
		company: "Lombard Architectes",
		subject: "Partenariat — projets tertiaires",
		body: "Bonjour,\n\nNous sommes un bureau d'architectes actif sur le tertiaire en Wallonie et souhaiterions explorer un partenariat pour vos projets de développement. Seriez-vous ouverts à un échange ?\n\nL'équipe Lombard",
		receivedAt: "2026-07-10T08:05:00Z",
		read: true,
		starred: false,
	},
];

export const PROPERTIES: Property[] = [
	{
		id: "p1",
		reference: "CI-2041",
		title: "Immeuble de bureaux clé-en-main",
		type: "office",
		status: "under_offer",
		transaction: "sale",
		city: "Wavre",
		address: "Zoning Nord, Wavre",
		price: 2450000,
		surface: 1800,
		description:
			"Immeuble tertiaire haut de gamme, entièrement rénové, 60 emplacements de parking, certification énergétique B.",
		addedAt: "2026-04-30T00:00:00Z",
		accent: "#3a4fff",
	},
	{
		id: "p2",
		reference: "CI-1987",
		title: "Entrepôt logistique avec quais",
		type: "warehouse",
		status: "under_offer",
		transaction: "sale",
		city: "Charleroi",
		address: "Parc logistique E42, Charleroi",
		price: 3800000,
		surface: 6500,
		description:
			"6 quais de chargement, hauteur libre 11 m, bureaux attenants 400 m², terrain adjacent disponible.",
		addedAt: "2026-05-15T00:00:00Z",
		accent: "#0ea5e9",
	},
	{
		id: "p3",
		reference: "CI-2088",
		title: "Surface commerciale de plain-pied",
		type: "retail",
		status: "available",
		transaction: "sale",
		city: "Liège",
		address: "Boulevard d'Avroy, Liège",
		price: 1750000,
		surface: 900,
		description:
			"Emplacement premium en artère commerçante, vitrine 22 m, forte fréquentation piétonne.",
		addedAt: "2026-06-05T00:00:00Z",
		accent: "#f59e0b",
	},
	{
		id: "p4",
		reference: "CI-2102",
		title: "Terrain agricole à développer",
		type: "land",
		status: "off_market",
		transaction: "sale",
		city: "Gembloux",
		address: "Route de Namur, Gembloux",
		price: 4200000,
		surface: 42000,
		description:
			"4,2 ha en zone à urbaniser, permis en cours d'instruction, proximité immédiate des axes autoroutiers.",
		addedAt: "2026-07-01T00:00:00Z",
		accent: "#10b981",
	},
	{
		id: "p5",
		reference: "CI-1954",
		title: "Immeuble de rapport 6 unités",
		type: "mixed",
		status: "sold",
		transaction: "sale",
		city: "Louvain-la-Neuve",
		address: "Grand-Place, Louvain-la-Neuve",
		price: 1650000,
		surface: 720,
		description:
			"Rez commercial + 5 appartements loués, rendement brut 6,2 %, entièrement occupé.",
		addedAt: "2026-03-20T00:00:00Z",
		accent: "#8b5cf6",
	},
	{
		id: "p6",
		reference: "CI-2115",
		title: "Plateau de bureaux centre-ville",
		type: "office",
		status: "available",
		transaction: "sale",
		city: "Namur",
		address: "Rue de Fer, Namur",
		price: 620000,
		surface: 240,
		description:
			"Plateau au 2e étage, standing élevé, 6 emplacements de parking privatifs, ascenseur.",
		addedAt: "2026-06-14T00:00:00Z",
		accent: "#3a4fff",
	},
	{
		id: "p7",
		reference: "CI-2076",
		title: "Hall industriel avec bureaux",
		type: "industrial",
		status: "available",
		transaction: "sale",
		city: "Seraing",
		address: "Zoning des Hauts-Sarts, Seraing",
		price: 2100000,
		surface: 3200,
		description:
			"Hauteur libre 9 m, pont roulant 10 t, puissance 400 kVA, bureaux 300 m² attenants.",
		addedAt: "2026-06-22T00:00:00Z",
		accent: "#64748b",
	},
	{
		id: "p8",
		reference: "CI-2130",
		title: "Showroom + atelier bord de nationale",
		type: "retail",
		status: "under_offer",
		transaction: "sale",
		city: "Arlon",
		address: "Route de Longwy, Arlon",
		price: 1980000,
		surface: 2400,
		description:
			"Showroom vitré 1 000 m², atelier 1 400 m², parking 40 véhicules, visibilité maximale.",
		addedAt: "2026-06-25T00:00:00Z",
		accent: "#f59e0b",
	},
	{
		id: "p9",
		reference: "CI-2144",
		title: "Cellule commerciale zone de chalandise",
		type: "retail",
		status: "available",
		transaction: "rent",
		city: "Wavre",
		address: "Centre commercial Les Carmes, Wavre",
		price: 4200,
		surface: 200,
		description:
			"Loyer mensuel, cellule d'angle, flux clients élevé, idéale franchise.",
		addedAt: "2026-07-03T00:00:00Z",
		accent: "#f59e0b",
	},
	{
		id: "p10",
		reference: "CI-2150",
		title: "Bureaux avec parking privatif",
		type: "office",
		status: "available",
		transaction: "sale",
		city: "Ottignies",
		address: "Avenue des Combattants, Ottignies",
		price: 890000,
		surface: 450,
		description:
			"Bureaux modulables, 15 emplacements de parking, proche gare et N4.",
		addedAt: "2026-06-11T00:00:00Z",
		accent: "#3a4fff",
	},
	{
		id: "p11",
		reference: "CI-1899",
		title: "Étude notariale — rez commercial",
		type: "office",
		status: "under_offer",
		transaction: "sale",
		city: "Tournai",
		address: "Rue Royale, Tournai",
		price: 730000,
		surface: 320,
		description:
			"Immeuble de caractère, rez commercial + étages, à quelques pas de la Grand-Place.",
		addedAt: "2026-05-29T00:00:00Z",
		accent: "#3a4fff",
	},
	{
		id: "p12",
		reference: "CI-2158",
		title: "Local commercial centre historique",
		type: "retail",
		status: "rented",
		transaction: "rent",
		city: "Nivelles",
		address: "Grand-Place, Nivelles",
		price: 1850,
		surface: 120,
		description:
			"Loyer mensuel, vitrine sur place piétonne, cave voûtée, récemment rénové.",
		addedAt: "2026-06-08T00:00:00Z",
		accent: "#f59e0b",
	},
];

export const CONTACTS: Contact[] = [
	{
		id: "c1",
		name: "Élise Vandenberghe",
		role: "Directrice des acquisitions",
		company: "Groupe Vandenberghe Invest",
		email: "e.vandenberghe@gv-invest.be",
		phone: "+32 475 21 44 08",
		type: "investor",
		city: "Bruxelles",
		lastContactAt: "2026-07-15T14:05:00Z",
		portfolioValue: 18500000,
	},
	{
		id: "c2",
		name: "Claire Dumont",
		role: "Family office",
		company: "Dumont Patrimoine",
		email: "c.dumont@dumont-patrimoine.be",
		phone: "+32 470 88 34 12",
		type: "investor",
		city: "Louvain-la-Neuve",
		lastContactAt: "2026-07-08T12:00:00Z",
		portfolioValue: 9200000,
	},
	{
		id: "c3",
		name: "Maître Antoine Gérard",
		role: "Notaire",
		company: "Étude Gérard",
		email: "a.gerard@notaire-gerard.be",
		phone: "+32 81 22 33 44",
		type: "notary",
		city: "Namur",
		lastContactAt: "2026-07-09T09:00:00Z",
	},
	{
		id: "c4",
		name: "Karim Benali",
		role: "CEO",
		company: "Benali Retail Group",
		email: "k.benali@benaliretail.be",
		phone: "+32 478 90 11 23",
		type: "tenant",
		city: "Liège",
		lastContactAt: "2026-07-13T11:40:00Z",
	},
	{
		id: "c5",
		name: "Michel Lecomte",
		role: "Propriétaire bailleur",
		company: "SCI Lecomte",
		email: "m.lecomte@sci-lecomte.be",
		phone: "+32 473 65 21 09",
		type: "owner",
		city: "Charleroi",
		lastContactAt: "2026-07-06T10:30:00Z",
		portfolioValue: 6400000,
	},
	{
		id: "c6",
		name: "Lombard Architectes",
		role: "Bureau partenaire",
		company: "Lombard Architectes",
		email: "contact@lombard-archi.be",
		phone: "+32 65 40 12 34",
		type: "partner",
		city: "Mons",
		lastContactAt: "2026-07-10T08:05:00Z",
	},
	{
		id: "c7",
		name: "Sandrine Collard",
		role: "Notaire",
		company: "Collard Notaires",
		email: "s.collard@collard-notaires.be",
		phone: "+32 471 65 43 21",
		type: "notary",
		city: "Tournai",
		lastContactAt: "2026-07-14T10:20:00Z",
	},
	{
		id: "c8",
		name: "Pierre-Yves Lambert",
		role: "Promoteur",
		company: "PYL Développement",
		email: "py.lambert@pyl-dev.be",
		phone: "+32 477 22 88 41",
		type: "investor",
		city: "Gembloux",
		lastContactAt: "2026-07-15T13:10:00Z",
		portfolioValue: 24000000,
	},
	{
		id: "c9",
		name: "BNP Paribas Fortis — Real Estate Finance",
		role: "Financement",
		company: "BNP Paribas Fortis",
		email: "re.finance@bnpparibasfortis.be",
		phone: "+32 2 762 00 00",
		type: "partner",
		city: "Bruxelles",
		lastContactAt: "2026-07-07T14:00:00Z",
	},
	{
		id: "c10",
		name: "Vincent Hubert",
		role: "Propriétaire",
		company: "Hubert Automotive",
		email: "v.hubert@hubert-auto.be",
		phone: "+32 498 30 22 66",
		type: "tenant",
		city: "Arlon",
		lastContactAt: "2026-07-13T14:50:00Z",
	},
];

export const TASKS: CrmTask[] = [
	{
		id: "t1",
		title: "Envoyer le rapport technique — bureaux Wavre",
		type: "document",
		dueAt: "2026-07-17T15:00:00Z",
		completed: false,
		owner: "Nicolas Dubois",
		relatedName: "Élise Vandenberghe",
		relatedLeadId: "l1",
	},
	{
		id: "t2",
		title: "Rappeler le promoteur (appel manqué région Liège)",
		type: "call",
		dueAt: "2026-07-17T11:00:00Z",
		completed: false,
		owner: "Camille Lefèvre",
	},
	{
		id: "t3",
		title: "Préparer le dossier terrain Gembloux",
		type: "document",
		dueAt: "2026-07-18T09:00:00Z",
		completed: false,
		owner: "Nicolas Dubois",
		relatedName: "Pierre-Yves Lambert",
		relatedLeadId: "l6",
	},
	{
		id: "t4",
		title: "Visite plateau de bureaux — Namur",
		type: "viewing",
		dueAt: "2026-07-21T14:00:00Z",
		completed: false,
		owner: "Camille Lefèvre",
		relatedName: "Aurélie Simon",
		relatedLeadId: "l3",
	},
	{
		id: "t5",
		title: "Vérifier l'option terrain adjacent — Charleroi",
		type: "follow_up",
		dueAt: "2026-07-18T16:00:00Z",
		completed: false,
		owner: "Thomas Mertens",
		relatedName: "Marc Delhaize",
		relatedLeadId: "l2",
	},
	{
		id: "t6",
		title: "Répondre à la contre-proposition — Tournai",
		type: "email",
		dueAt: "2026-07-17T17:00:00Z",
		completed: false,
		owner: "Camille Lefèvre",
		relatedName: "Sandrine Collard",
		relatedLeadId: "l13",
	},
	{
		id: "t7",
		title: "Organiser la visite showroom — Arlon",
		type: "viewing",
		dueAt: "2026-07-19T10:00:00Z",
		completed: false,
		owner: "Thomas Mertens",
		relatedName: "Vincent Hubert",
		relatedLeadId: "l14",
	},
	{
		id: "t8",
		title: "Qualifier la nouvelle demande — Mons",
		type: "call",
		dueAt: "2026-07-17T13:30:00Z",
		completed: false,
		owner: "Sophie Laurent",
		relatedName: "Isabelle Moreau",
		relatedLeadId: "l5",
	},
	{
		id: "t9",
		title: "Réunion d'équipe hebdomadaire — pipeline",
		type: "meeting",
		dueAt: "2026-07-20T08:30:00Z",
		completed: false,
		owner: "Nicolas Dubois",
	},
	{
		id: "t10",
		title: "Transmettre les caractéristiques techniques — Seraing",
		type: "email",
		dueAt: "2026-07-16T17:00:00Z",
		completed: true,
		owner: "Thomas Mertens",
		relatedName: "David Peeters",
		relatedLeadId: "l8",
	},
	{
		id: "t11",
		title: "Signature acte — immeuble de rapport LLN",
		type: "meeting",
		dueAt: "2026-07-08T11:00:00Z",
		completed: true,
		owner: "Nicolas Dubois",
		relatedName: "Claire Dumont",
		relatedLeadId: "l9",
	},
];

export const ACTIVITIES: Activity[] = [
	{
		id: "a1",
		kind: "new_lead",
		actor: "Sophie Laurent",
		summary: "Nouveau lead reçu — Isabelle Moreau (immeuble mixte, Mons)",
		at: "2026-07-16T07:50:00Z",
	},
	{
		id: "a2",
		kind: "message",
		actor: "Standard",
		summary: "Appel manqué d'un promoteur — portefeuille 3 immeubles à Liège",
		at: "2026-07-16T09:12:00Z",
	},
	{
		id: "a3",
		kind: "stage_change",
		actor: "Nicolas Dubois",
		summary: "Élise Vandenberghe passée en Négociation (2,45 M€)",
		at: "2026-07-15T14:05:00Z",
	},
	{
		id: "a4",
		kind: "new_lead",
		actor: "Nicolas Dubois",
		summary: "Opportunité off-market — terrain Gembloux (4,2 M€)",
		at: "2026-07-15T13:10:00Z",
	},
	{
		id: "a5",
		kind: "message",
		actor: "Camille Lefèvre",
		summary: "Contre-proposition reçue — étude notariale Tournai",
		at: "2026-07-14T10:20:00Z",
	},
	{
		id: "a6",
		kind: "viewing",
		actor: "Thomas Mertens",
		summary: "Visite planifiée — showroom Arlon (Vincent Hubert)",
		at: "2026-07-13T14:50:00Z",
	},
	{
		id: "a7",
		kind: "deal_won",
		actor: "Nicolas Dubois",
		summary: "Affaire gagnée — immeuble de rapport LLN (1,65 M€)",
		at: "2026-07-08T12:00:00Z",
	},
	{
		id: "a8",
		kind: "note",
		actor: "Camille Lefèvre",
		summary: "Note ajoutée sur Karim Benali — expansion 3 emplacements",
		at: "2026-07-13T11:45:00Z",
	},
];
